//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DL_EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Asistencia
    {
        public int IdAsistencia { get; set; }
        public string Email { get; set; }
        public string Titulo { get; set; }
        public string Mensaje { get; set; }
        public System.DateTime FechaUp { get; set; }
        public Nullable<System.DateTime> FechaDown { get; set; }
        public int IdEstatus { get; set; }
    
        public virtual EstatusAsistencia EstatusAsistencia { get; set; }
    }
}
