//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DL_EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Paquete
    {
        public int IdPaquete { get; set; }
        public string InstruccionEntrega { get; set; }
        public decimal Peso { get; set; }
        public string DireccionOrigen { get; set; }
        public string DireccionEntrega { get; set; }
        public System.DateTime FechaEstimadaEntrega { get; set; }
        public string NumeroGuia { get; set; }
        public byte[] CodigoQR { get; set; }
    }
}
